### ISSUE TITLE
dashboard_v1.Dashboard.from_json unable to parse json.

### ISSUE THREAD

**Issue by deepak1725** [googleapis/python-monitoring-dashboards#231] opened 2022-09-16 15:33 UTC
#### Environment details

  - OS type and version: Mac Monterey
  - Python version: `python --version`: 3.9
  - pip version: `pip --version` pip 22.2.2
  - `google-cloud-monitoring-dashboards` version: `pip show google-cloud-monitoring-dashboards` 2.7.2

#### Steps to reproduce

  1. Take a Dump: `gcloud monitoring dashboards describe projects/{project_id}/dashboards/{dash_id} >> dashboard.json`
  2. Read Json in Python and load it in a variable
  3. Try to clone it in another Project via Python Client.
  
#### Code example

```python
from google.monitoring import dashboard_v1
import yaml
import json

with open("path/dashboard.yml") as f:
    dashboard_json = yaml.safe_load(f)
    dashboard = dashboard_v1.Dashboard.from_json(json.dumps(dashboard_json))
    print(dashboard)
```

#### Stack trace
```
dashboard = dashboard_v1.Dashboard.from_json(json.dumps(db))
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/proto/message.py", line 421, in from_json
    Parse(payload, instance._pb, ignore_unknown_fields=ignore_unknown_fields)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/protobuf/json_format.py", line 436, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/protobuf/json_format.py", line 461, in ParseDict
    parser.ConvertMessage(js_dict, message, '')
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/protobuf/json_format.py", line 502, in ConvertMessage
    self._ConvertFieldValuePair(value, message, path)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/google/protobuf/json_format.py", line 629, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "google.monitoring.dashboard.v1.Dashboard" has no field named "mosaicLayout" at "Dashboard"."
```

**Comment by vam-google** [comment] 2022-09-23 18:17
Hi @deepak1725,

Please check what's inside your json. The code snippet you provided does not completely correspond to the steps, as code snippet loads from `.yaml` then dumps to `json` and only then reads from json.

I've just tried the following example:
```py
    db = dashboard_v1.Dashboard(
        etag="mytag",
        name="my_name",
        mosaic_layout=dashboard_v1.MosaicLayout(columns=2)
    )
    db_json = dashboard_v1.Dashboard.to_json(db)

    print("--------------")
    print(db_json)
    print("--------------")

    db_from_json = dashboard_v1.Dashboard.from_json(db_json)

    print("++++++++++++++")
    print(db_from_json)
    print("++++++++++++++")
```

Which works just fine and outputs the following:

```
--------------
{
  "name": "my_name",
  "etag": "mytag",
  "mosaicLayout": {
    "columns": 2,
    "tiles": []
  },
  "displayName": "",
  "dashboardFilters": [],
  "labels": {}
}
--------------
++++++++++++++
name: "my_name"
etag: "mytag"
mosaic_layout {
  columns: 2
}

++++++++++++++
```

So if I had to guess, there is something problematic in  your specific json you are trying to parse (and maybe something went wrong in that yaml-json conversion as well). 

Closing for now, as it is very unlikely that the issue is int the client's code. Feel free to reopen if you can confirm that the json you are trying to parse is indeed a valid one.

**Closed by vam-google** 2022-09-23 18:17 UTC
Labels: type: bug, priority: p2, api: monitoring
